### ISSUE TITLE
Cannot read properties of null (reading 'location')

### ISSUE THREAD

**Issue by OsirisFrik** [minodisk/bigquery-runner#49]
Hi, I have this error when I run the query and try to render the result table,
It had been working correctly until it started giving that error

```bash
2023-12-13 14:51:05.515 [error] TypeError: Cannot read properties of null (reading 'location')
    at Th (/home/osiris/.vscode/extensions/minodisk.bigquery-runner-1.21.4/out/extension/index.js:90:11864)
    at /home/osiris/.vscode/extensions/minodisk.bigquery-runner-1.21.4/out/extension/index.js:90:11622
    at Array.forEach (<anonymous>)
    at rP (/home/osiris/.vscode/extensions/minodisk.bigquery-runner-1.21.4/out/extension/index.js:90:11607)
    at /home/osiris/.vscode/extensions/minodisk.bigquery-runner-1.21.4/out/extension/index.js:90:10977
    at Array.map (<anonymous>)
    at Object.getNumberedRows (/home/osiris/.vscode/extensions/minodisk.bigquery-runner-1.21.4/out/extension/index.js:90:10959)
    at Object.renderRows (/home/osiris/.vscode/extensions/minodisk.bigquery-runner-1.21.4/out/extension/index.js:109:14736)
    at Object.run (/home/osiris/.vscode/extensions/minodisk.bigquery-runner-1.21.4/out/extension/index.js:109:18081)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at bigqueryRunner.run (/home/osiris/.vscode/extensions/minodisk.bigquery-runner-1.21.4/out/extension/index.js:111:6325)
    at d.h (/snap/code/147/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:141:140086) bigqueryRunner.run {"value":"minodisk.bigquery-runner","_lower":"minodisk.bigquery-runner"}
```

**Comment by minodisk** [comment]
How about setting [bigqueryRunner.location](https://github.com/minodisk/bigquery-runner?tab=readme-ov-file#bigqueryrunnerlocation) in settings.json?
